flaskapp/appname/controllers/algorithms.py
from flask import (Blueprint,
                   render_template,
                   flash,
                   redirect,
                   url_for, request, json, jsonify)
from flask.ext.login import login_required
from appname.extensions import cache
from appname.forms import (AlgorithmForm,
                           ImplementationForm,
                           AlgorithmViewForm)
from appname.models import (db,
                            Tag,
                            Algorithm,
                            Implementation, URL)
from appname.controllers.constants import (URLS, SCRIPTS)
from flask_table import (Table, Col)


algorithms = Blueprint('algorithms', __name__)


@algorithms.route('/')
@cache.cached(timeout=1000)
@login_required
def algorithm():
    """ """
    return render_template('algorithms.html',
                           algorithm_form=create_algorithm_form(),
                           implementation_form=create_implementation_form(),
                           alg_table=create_algorithm_table(),
                           imp_table=create_implementation_table(),
                           display_all_form=create_view_form())


@algorithms.route('/submit_algorithm', methods=["Post"])
@cache.cached(timeout=1000)
@login_required
def submit_algorithm():
    """ """
    algorithm_form = create_algorithm_form()
    if algorithm_form.validate_on_submit():
        db.session.add(Algorithm(name=algorithm_form.name.data,
                                 description=algorithm_form.description.data,
                                 tags=[Tag.query.filter_by(id=_id).first()
                                       for _id in algorithm_form.tags.data]))
        db.session.commit()
        flash("New algorithm added successfully.", "success")
        return redirect(url_for("algorithms.algorithm"))
    flash('Failed validation', 'danger')
    return render_template('algorithms.html',
                           algorithm_form=algorithm_form,
                           implementation_form=create_implementation_form(),
                           alg_table=create_algorithm_table(),
                           imp_table=create_implementation_table(),
                           display_all_form=create_view_form())


@algorithms.route('/submit_implementation', methods=["Post"])
@cache.cached(timeout=1000)
@login_required
def submit_implementation():
    """ """
    implementation_form = create_implementation_form()
    if implementation_form.validate_on_submit():
        db.session.add(Implementation(
            algorithm_id=implementation_form.algorithm.data,
            name=implementation_form.name.data,
            description=implementation_form.description.data,
            tags=[Tag.query.filter_by(id=_id).first()
                  for _id in implementation_form.tags.data],
            urls=[url_form.url.data for url_form in
                  implementation_form.url_forms],
            setup_scripts=[script.path.data for script in
                           implementation_form.setup_scripts],
            executable=implementation_form.executable.data))
        db.session.commit()
        flash("New implementation added successfully", "success")
        return redirect(url_for("algorithms.algorithm"))
    flash('Failed validation', 'danger')
    return render_template('algorithms.html',
                           algorithm_form=create_algorithm_form(),
                           implementation_form=implementation_form,
                           alg_table=create_algorithm_table(),
                           imp_table=create_implementation_table(),
                           display_all_form=create_view_form())

@algorithms.route('/narrow', methods=['POST', 'GET'])
def narrow():
    data = json.loads(request.form.get('data'))
    algid = data['algid']
    imps = '<option value="0">Select Implementation</option>'
    tag_ret = ''
    for entry in Implementation.query.filter(Implementation._algorithm_id == algid).all():
        imps += '<option value="%i">%s</option>' % (entry.id, entry._name)
    name = Algorithm.query.filter(Algorithm.id==algid).first().name
    descr = Algorithm.query.filter(Algorithm.id==algid).first().description
    tags = [tag.name for tag in Tag.query.filter(Tag.algorithms.any(id=algid)).all()]
    for tag in tags:
        tag_ret += '<p>%s</p>' % tag
    return jsonify({'imps':imps, 'name':name, 'descr':descr, 'tags':tag_ret})

@algorithms.route('/select_imp', methods=['POST', 'GET'])
def select_imp():
    data = json.loads(request.form.get('data'))
    impid = data['impid']
    url_ret = ''
    script_ret = ''
    tag_ret = ''
    name = Implementation.query.filter(Implementation.id==impid).first().name
    alg = Algorithm.query.filter(Algorithm.implementations.any(id=impid)).first().name
    exe = Implementation.query.filter(Implementation.id==impid).first().executable
    descr = Implementation.query.filter(Implementation.id==impid).first().description
    tags = [tag.name for tag in Tag.query.filter(Tag.implementations.any(id=impid)).all()]
    urls = [url.url for url in URL.query.filter(URL.implementation.has(id=impid)).all()]
    scripts = Implementation.query.filter(Implementation.id==impid).first().setup_scripts
    for scr in scripts:
        script_ret += '<p>%s</p>' % scr
    for tag in tags:
        tag_ret += '<p>%s</p>' % tag
    for url in urls:
        url_ret += '<p>%s</p>' % url
    return jsonify({'name':name, 'alg':alg, 'urls':url_ret, 'scripts':script_ret, 'exe':exe, 'descr':descr, 'tags':tag_ret})


class AlgTable(Table):
    id = Col('Algorithm ID')
    name = Col('Algorithm Name')
    description = Col('Description')
    tags = Col('Tags')

    def tr_format(self, item):
        return '<tr valign="top">{}</tr>'


class ImpTable(Table):
    id = Col('Implementation ID')
    name = Col('Implementation Name')
    description = Col('Description')
    executable = Col('Executable')
    alg = Col('Associated Algorithm')
    urls = Col('URL')
    tags = Col('Tags')

    def tr_format(self, item):
        return '<tr valign="top">{}</tr>'


class AlgItem(object):
    def __init__(self, id, name, description, tags):
        self.name = name
        self.id = id
        self.description = description
        self.tags = tags


class ImpItem(object):
    def __init__(self, id, name, description, executable, alg, urls, tags):
        self.name = name
        self.id = id
        self.description = description
        self.executable = executable
        self.alg = alg
        self.urls = urls
        self.tags = tags


def create_algorithm_table():
    """ """
    return AlgTable([AlgItem(
        alg.id,
        alg.name,
        alg.description,
        '\n'.join([str(tag.name) for tag in Tag.query.filter(
            Tag.algorithms.any(id=alg.id)).all()]))
        for alg in Algorithm.query.all()])


def create_implementation_table():
    """ """
    return ImpTable([ImpItem(
        imp.id,
        imp.name,
        imp.description,
        imp.executable,
        Algorithm.query.filter(Algorithm.implementations.any(
            id=imp._algorithm_id)).first().name,
        '\n'.join([str(url._url) for url in imp._urls]),
        '\n'.join([tag.name for tag in Tag.query.filter(
            Tag.implementations.any(id=imp.id)).all()]))
        for imp in Implementation.query.all()])


def create_algorithm_form():
    """ """
    form = AlgorithmForm()
    form.tags.choices = [(t.id, t.name) for t in Tag.query.order_by('_name')]
    return form


def create_implementation_form():
    """ """
    form = ImplementationForm(url_forms=URLS, setup_scripts=SCRIPTS)
    form.algorithm.choices = [(a.id, a.name) for a in
                              Algorithm.query.order_by('_name')]
    form.tags.choices = [(t.id, t.name) for t in Tag.query.order_by('_name')]
    return form

def create_view_form():
    display_all_form = AlgorithmViewForm()
    display_all_form.algorithms.choices = [(0, 'Select Algorithm')]+[(da.id, da.name) for da in
                                                                     Algorithm.query.order_by('_name')]
    display_all_form.implementations.choices = [(0, 'Select Implementation')]
    return display_all_form

flaskapp/appname/controllers/tags.py
from flask import (Blueprint,
                   render_template,
                   flash,
                   redirect,
                   url_for)
from flask.ext.login import login_required
from appname.extensions import cache
from appname.forms import TagForm
from appname.models import (db, Tag)
from flask_table import (Table, Col)


tags = Blueprint('tags', __name__)


@tags.route('/')
@cache.cached(timeout=1000)
@login_required
def tag():
    return render_template('tags.html',
                           tag_form=TagForm(),
                           tag_table=TagTable(Tag.query.all()))


@tags.route('/submit_tag', methods=["Post"])
@cache.cached(timeout=1000)
@login_required
def submit_tag():
    tag_form = TagForm()
    if tag_form.validate_on_submit():
        db.session.add(Tag(tag_form.name.data))
        db.session.commit()
        flash("Tag added successfully.", "success")
        return redirect(url_for("tags.tag"))
    flash("Failed validation", "danger")
    return render_template('tags.html',
                           tag_form=tag_form,
                           tag_table=TagTable(Tag.query.all()))


class TagTable(Table):
    id = Col('Tag ID')
    name = Col('Tag Name')

flaskapp/squall/__init__.py
#! ../env/bin/python

from flask import Flask
from webassets.loaders import PythonLoader as PythonAssetsLoader

from squall import assets
from squall.models import (db,
                           mongo)
from squall.controllers import (main,
                                algorithms,
                                data,
                                experiments,
                                tags)

from squall.extensions import (
    cache,
    assets_env,
    debug_toolbar,
    login_manager
)


def create_app(object_name, env="prod"):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. squall.settings.ProdConfig

        env: The name of the current environment, e.g. prod or dev
    """

    app = Flask(__name__)

    app.config.from_object(object_name)
    app.config['ENV'] = env

    # initialize the cache
    cache.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)
    login_manager.init_app(app)

    # initialize MongoDB
    mongo.init_app(app)

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # register our blueprints
    app.register_blueprint(main)
    app.register_blueprint(algorithms, url_prefix='/algorithms')
    app.register_blueprint(data, url_prefix='/data')
    app.register_blueprint(experiments, url_prefix='/experiments')
    app.register_blueprint(tags, url_prefix='/tags')

    return app

flaskapp/squall/controllers/__init__.py
from main import main
from algorithms import algorithms
from data import data
from experiments import experiments
from tags import tags

__all__ = [main,
           algorithms,
           data,
           experiments,
           tags]

flaskapp/squall/controllers/constants.py
""" Constant To Pre-Populate Forms """
# BatchForm
MEMORY = 4096
DISK = 10485760
FLOCK = True
GLIDE = True
# DataSetForm & ImplementationForm
URLS = [{'url': "http://proxy.chtc.wisc.edu/SQUID/"}]

SCRIPTS = [{'path': "full/path/to/script"}]

flaskapp/squall/controllers/main.py
from flask import (Blueprint,
                   render_template,
                   flash, request,
                   redirect,
                   url_for, json, jsonify)
from flask.ext.login import (login_user,
                             logout_user,
                             login_required, current_user)

from squall.extensions import cache
from squall.forms import LoginForm, CreateUserForm, UserViewForm, EditUserForm
from squall.models import db, User
from werkzeug.security import generate_password_hash

main = Blueprint('main', __name__)


@main.route('/')
@cache.cached(timeout=1000)
def home():
    return render_template('index.html')


@main.route("/login", methods=["GET", "POST"])
def login():
    # if g.user is not None and g.user.is_authenticated:
        #  return redirect(url_for('restricted'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()
        login_user(user)
        flash("Logged in successfully.", "success")
        return redirect(request.args.get("next") or url_for(".home"))
    flash("Failed validation", "danger")
    return render_template("login.html", form=form)


@main.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out.", "success")
    return redirect(url_for(".home"))


@main.route("/restricted")
@login_required
def user():
    return render_template("create_user.html", form=CreateUserForm(),
                           display_all_form=create_view_form(),
                           edit_form=create_edit_form())


@main.route("/create_user", methods=["Get", "Post"])
@login_required
def create_user():
    form = CreateUserForm()
    if form.validate_on_submit():
        user = User(form.username.data,
                    form.launch_directory.data,
                    form.password.data)
        db.session.add(user)
        db.session.commit()
        flash("New user created successfully.", "success")
        return redirect(url_for(".home"))

    flash("Failed validation", "danger")
    return render_template("create_user.html", form=form,
                           display_all_form=create_view_form(),
                           edit_form=create_edit_form())


@main.route("/edit_user", methods=["GET", "POST"])
@login_required
def edit_user():
    edit_form = create_edit_form()
    curr_user = User.query.filter_by(id=current_user.get_id()).first()
    if edit_form.validate_on_submit():
        curr_user.password = generate_password_hash(edit_form.edit_pw.data)
        db.session.commit()
        curr_user.launch_directory = edit_form.edit_dir.data
        db.session.commit()
        flash("User information updated", "success")
        return redirect(url_for(".home"))

    flash("Failed validation", "danger")
    return render_template("create_user.html", form=CreateUserForm(),
                           display_all_form=create_view_form(),
                           edit_form=edit_form)


@main.route('/select_user', methods=['POST', 'GET'])
def select_user():
    userid = json.loads(request.form.get('data'))['userid']
    return jsonify({'name': User.query.filter(
        User.id == userid).first().username, 'dir': User.query.filter(
            User.id == userid).first()._launch_directory})


@main.route('/get_curr_dir', methods=['POST', 'GET'])
def get_curr_dir():
    curr_user = User.query.filter_by(id=current_user.get_id()).first()
    return jsonify({'dir': curr_user.launch_directory})


def create_view_form():
    display_all_form = UserViewForm()
    display_all_form.users.choices = [(0, 'Select User')] + [
        (u.id, u.username) for u in User.query.order_by('username')]
    return display_all_form


def create_edit_form():
    edit_form = EditUserForm()
    edit_form.edit_username.data = User.query.filter_by(
        id=current_user.get_id()).first().username
    return edit_form

flaskapp/squall/controllers/tags.py
from flask import (Blueprint,
                   render_template,
                   flash,
                   redirect,
                   url_for)
from flask.ext.login import login_required
from squall.extensions import cache
from squall.forms import TagForm
from squall.models import (db, Tag)
from flask_table import (Table, Col)


tags = Blueprint('tags', __name__)


@tags.route('/')
@cache.cached(timeout=1000)
@login_required
def tag():
    return render_template('tags.html',
                           tag_form=TagForm(),
                           tag_table=TagTable(Tag.query.all()))


@tags.route('/submit_tag', methods=["Post"])
@cache.cached(timeout=1000)
@login_required
def submit_tag():
    tag_form = TagForm()
    if tag_form.validate_on_submit():
        db.session.add(Tag(tag_form.name.data))
        db.session.commit()
        flash("Tag added successfully.", "success")
        return redirect(url_for("tags.tag"))
    flash("Failed validation", "danger")
    return render_template('tags.html',
                           tag_form=tag_form,
                           tag_table=TagTable(Tag.query.all()))


class TagTable(Table):
    id = Col('Tag ID')
    name = Col('Tag Name')

flaskapp/squall/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% assets "common_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {% endassets %}

        {% block css %}
        {% endblock %}

        <script src="{{ url_for('static', filename='js/vendor/modernizr.min.js') }}"></script>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Squall</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                  <li><a href="{{ url_for('main.home') }}">Home</a></li>
		  <li><a href="{{ url_for('algorithms.algorithm') }}">Algorithms</a></li>
		  <li><a href="{{ url_for('data.collection') }}">Data</a></li>
		  <li><a href="{{ url_for('experiments.experiment') }}">Experiments</a></li>
		  <li><a href="{{ url_for('main.user') }}">Users</a></li>
		  <li><a href="{{ url_for('tags.tag') }}">Tags</a></li>		  
                    {% if not current_user.is_authenticated %}
                        <li><a href="{{ url_for('main.login') }}">Login</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.logout') }}">Logout</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>

        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block body %}
            {% endblock %}
        </div>

        {% assets "common_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}
        
        {% block js %}
        {% endblock %}
    </body>
</html>

flaskapp/squall/templates/create_user.html
{% extends "base.html" %}

{% block title %} Users {% endblock %}

{% block body %}

<style>
    p { margin:0 }
    #user_form {
        display:none;
    }
#edit_form {
    display:none;
}
.info_title {
    font-weight:bold;
}
#user_info {
    display:none;
}

    </style>

<div class="row">
    <h1 class="text-center">View All Users</h1>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form role="form">
            <div class="form-group">
                <h4>{{ display_all_form.users.label }}</h4>
                {{ display_all_form.users(class_="form-control") }}
            </div>
            <div id="user_info">
                <p class="info_title">Name:</p>
                <p class="user_val" id="user_name"></p>
                <p class="info_title">HTCondor Submit Node Launch Directory:</p>
                <p class="user_val" id="user_dir"></p>
            </div>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>
<br />

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <button class="btn btn-block" id="user_button">Create New User</button>
    </div>
    <div class="col-md-4"></div>
</div>

<div class="row" id="user_form">
    <h1 class="text-center">Create User</h1>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form role="form" action="{{ url_for('.create_user') }}" method="post">
            {{ form.hidden_tag() }}
            
            <div class="form-group">
                {{ form.username.label }}
                {% if form.username.errors %}
                {% for e in form.username.errors %}
                <p class="help-block">{{ e }}</p>
                {% endfor %}{% endif %}
                {{ form.username(class_="form-control") }}
            </div>
            <div class="form-group">
                <p>{{ form.launch_directory.label }}
                <button class="btn btn-xs" onclick="toggleButton('create_user_button', 'create_user_info', 'Choose the directory on the HTCondor submit node that is intended to submit jobs from. <strong>[Required]</strong>')" type="button" id="create_user_button">info</button></p>
                <p id="create_user_info"></p>
                
                {% if form.launch_directory.errors %}
                {% for e in form.launch_directory.errors %}
                <p class="help-block">{{ e }}</p>
                {% endfor %}{% endif %}
                {{ form.launch_directory(class_="form-control") }}
            </div>
            
            <div class="form-group">
                {{ form.password.label }}
                {% if form.password.errors %}
                {% for e in form.password.errors %}
                <p class="help-block">{{ e }}</p>
                {% endfor %}{% endif %}
                {{ form.password(class_="form-control") }}
            </div>
            
            <button id="create_submit" type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>

<br/>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <button class="btn btn-block" id="edit_button">Edit User Information</button>
    </div>
    <div class="col-md-4"></div>
</div>
<div class="row" id="edit_form">
    <h1 class="text-center">Edit User</h1>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form role="form" action="{{ url_for('.edit_user') }}" method="post">
            {{ edit_form.hidden_tag() }}
            
            <div class="form-group">
                <p>{{ edit_form.edit_username.label }}
                <div id="edit_display_name"></div></p>
                {% if edit_form.edit_username.errors %}
                {% for e in edit_form.edit_username.errors %}
                <p class="help-block">{{ e }}</p>
                {% endfor %}{% endif %}
                {{ edit_form.edit_username(class_="form-control", readonly=true) }}
            </div>
            <div class="form-group">
                <p>{{ edit_form.edit_dir.label }}
                <button class="btn btn-xs" onclick="toggleButton('edit_user_button', 'edit_user_info', 'Choose the directory on the HTCondor submit node that is intended to submit jobs from. <strong>[Required]</strong>')" type="button" id="edit_user_button">info</button></p>
                <p id="edit_user_info"></p>
                
                {% if edit_form.edit_dir.errors %}
                {% for e in edit_form.edit_dir.errors %}
                <p class="help-block">{{ e }}</p>
                {% endfor %}{% endif %}
                {{ edit_form.edit_dir(class_="form-control") }}
            </div>
            
            <div class="form-group">
                {{ edit_form.edit_pw.label }}
                {% if edit_form.edit_pw.errors %}
                {% for e in edit_form.edit_pw.errors %}
                <p class="help-block">{{ e }}</p>
                {% endfor %}{% endif %}
                {{ edit_form.edit_pw(class_="form-control") }}
            </div>
            
            <button id="edit_submit" type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>

<script src="https://code.jquery.com/jquery-2.1.4.js"></script>
<script src="{{ url_for("static", filename="js/create_user.js") }}"></script>
<script src="{{ url_for("static", filename="js/toggle.js") }}"></script>
{% endblock %}

flaskapp/squall/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block body %}
    <div>
        <img class="img-rounded" style="width:100%;" id="image" src="/static/squall_name1.png">
    </div>
    <div class="jumbotron">
        <h1>Squall</h1>
        <h4><i><small>~ a sudden, sharp increase in wind speed that is usually associated with active weather, such as rain showers, thunderstorms, or heavy snow (Wikipedia)</small></i></h4>
        <p>An Intuitive Tool for More Efficient Research</p>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h1>Why Squall?</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h3>Intuitive User Interface</h3>
            <p>Built with <a href="http://flask.pocoo.org" target="_blank">Flask</a> and tested with users having a wide range of high throughput computing knowledge, Squall delivers a powerful tool for everyone to easily, quickly, and accurately perform large scale computations with the University of Wisconsin - Madison's <a href="https://research.cs.wisc.edu/htcondor/description.html" target="_blank">HTCondor</a> high throughput computing software.</p>
            <p>Navigate the tabs at the top of the page to create the necessary components for jobs, the fundamental unit of execution in high throughput computing.</p>
        </div>

        <div class="col-md-4">
            <h3>Robust Queriable Databases</h3>
            <p>The use of multiple types of databases allows Squall to more efficiently handle user information. The <a href="" target="_blank">SQLite</a> database stores user input to the web application and is known for it's simplicity and ease of use. Complementing SQLite, the <a href="" target="_blank">MongoDB</a> handling user submission and results files for HTCondor, as a more flexible database is needed to properly store unpredictable and variable data.</p>
        </div>

        <div class="col-md-4">
            <h3>Distributed Computing Functionality</h3>
            <p>Squall provides high throughput functionality through UW - Madison's HTCondor. As a specialized workload management system for compute-intensive jobs, HTCondor harnesses the power of both dedicated servers and otherwise wasted CPU power from idle desktop workstations throughout the univeristy.</p>
            <p>HTCondor can also extend it's computing 'grid' to encompass more computing resources from other universities and research institutions across the nation and across the globe.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h1>Additional Information</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h3>GitHub Repository</h3>
            <p>Intimately explore Squall and help to improve the system <a href="https://github.com/ikinsella/squall" target="_blank">here</a>.</p>
        </div>

    <div class="col-md-4">
        <h3>Squall Wiki</h3>
            <p>Learn more about the Squall project <a href="https://github.com/ikinsella/squall/wiki" target="_blank">here</a>.</p>
        </div>
    </div>
{% endblock %}

flaskapp/squall/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block body %}
    <h1 class="text-center">Login</h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form role="form" action="{{ url_for('.login') }}" method="post">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                    {% for e in form.username.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}{% endif %}
                    {{ form.username(class_="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                    {% for e in form.password.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}{% endif %}
                    {{ form.password(class_="form-control") }}
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}

flaskapp/squall/templates/tags.html
{% extends "base.html" %}

{% block title %} Tags {% endblock %}

{% block body %}

<div class="row">
    <h1 class="text-center">Tags</h1>
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form role="form" action="{{ url_for('.submit_tag') }}" method="post">
            {{ tag_form.hidden_tag() }}
            
            <div class="form-group">
                <p>{{ tag_form.name.label }}
                <button class="btn btn-xs" onclick="toggleButton('tags_name_button', 'tags_name_info', 'Used to add meta-data to other objects.')" type="button" id="tags_name_button">info</button></p>
                <p id="tags_name_info"></p>
                
                {% if tag_form.name.errors %}
                {% for e in tag_form.name.errors %}
                <p class="help-block">{{ e }}</p>
                {% endfor %}{% endif %}
                {{ tag_form.name(class_="form-control") }}
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="col-md-4"></div>
</div>
<!--<hr>-->
<!--<div class="row">-->
<!--    <div class="col-md-4"></div>-->
<!--    <style>-->
<!--        th, td {-->
<!--            padding-left: 8px;-->
<!--            padding-right: 8px;-->
<!--        }-->
<!--    </style>-->
<!--    <pre>-->
<!--    {{ tag_table }}-->
<!--    </pre>-->
<!--    <div class="col-md-4"></div>-->
<!--</div>-->

<script src="{{ url_for("static", filename="js/toggle.js") }}"></script>
{% endblock %}